BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBB

XXXXX XXXXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXX XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFF FFFFF FFFFFFFFFFFFF

        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXX XXXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFF FFFFF FFFFFFFFFFFFF
        XXXXXX
    XXXXXX
    XXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX
    XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXX X XXXXXXXXXXXX                      
        BBBB BBBBBBBBBBBBB
        BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB

        BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBB BB BBBBBBBB
                BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
                  XX XXXXXXXX XXXXXXX X XXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBXXXXXX
                BBBBBB
            BBBBB
            XX XXXXXXXX XXXXXXXX XXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
                XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX
            XXXX
        BBBBBB
    XXXXXX
    XXXX XXXXXXXXXX XXX XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
    XXXXXX
XXXXXXX