BBBB BBBBBBBBBBBBB

XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXX XXXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFF FFFFF FFFFFFFFFFFFF
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXX XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFF FFFFF FFFFFFFFFFFFF
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXX XXXXX
            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFF FFFFF FFFFFFFFFFFFF
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXX XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFF FFFFF FFFFFFFFFFFFF
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXX XXX XXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXXX