BBBB BBBBBB

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXX XXX XX XXXXXXXXXXX
            XX XXXXXXXXX
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
            XXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX
        XXXXXX
    XXXXXX
    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XX XXXXXXBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
                BB BBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                BBBB
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
                BBBBB
                    XXXXX XXXXXXXXXXXXXXXXX XXXXXX XX XXXXXXX
                XXXX
            XXXXXX
        XXXXX
        XXXX
            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXX
        XXXX
            XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBXXBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
    XXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX
                XXXX
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXX
                        XXXX XXXXXXXXXX XXXX                            
                            XX XXXXXXBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
                                BB BBBBBBBBBBBBBBBBBBB
                                    XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                                BBBB
                                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
                                BBBBB
                            XXXX
                        XXXXXX
                        XXXX XXXXXXXXXX XXXX
                            XX XXXXXXBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
                                XXXX XXXXXXXXXXX
                            XXXX
                        XXXXXX
                    XXXXXX
                XXXXX
                XXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXX
                XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                XXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                XXX XXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBXXBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
            XXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBB
