XXXXXXXXX XXXXX
BBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBB
XXXXX XXXXXXXXXX
XXXXXX
    XXXXXXXXXX XXXXXX XXXX XXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
    XXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
    XXXXXXX XXXXXXX XXXX XXXXXXX XX XXXXXXXXX XXX XXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX X XXXXXX XXXXXXXXXX XXXX XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXBB BBBBBBBB X XXXXX XXXXBBBBXXXXX XXXXBBBBBXXXXXXXX
    XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
			        XXXX XXXXXXXXXXXX XXXXXXXXXXX
			            XXXX XXXXXXXXXXXXX
			                XX XXXXXXXXX
			                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
			                XXXX
			            XXXXXX
			        XXXXXX
			    XXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXX
                BBBBB BBBBBBB
					XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
							XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXX XXXXX
									XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
								XXXXXX
							XXXXXX
						XXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
							XXXX XXXXXXXXXXXX
								XXXX XXXXXXXXXX XXXXX
									XXXXX XXX XXXXXXXX XXXXXX XXXXXXXXX XXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XX XXXXXX XXXXXXXXXXX
								XXXXXX
								XXXX XXXXXXXXXX XXX XXXXXXXX
						        	XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
						        XXXXXX
							XXXXXX
						XXXXXX
					XXXXXXXXXX
                BBBBBBBB
            XXXXXX
        XXXXXX
    XXXXXX
    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XX XXXXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXX XX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    
    BBBBB BBBBBBBBBB
XXXXXXX
XXXXXXX