BBBB BBBBBBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXX
                XXX XXXXXXXXXXXXX
                    XXX XXXXXXXXXX XXX XX XX XX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                    XXXX XXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXX XXX XX XX XX XXXXXXXXX XXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                    XXXX XXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBB XXXXXXXXXXXXXXXXXX XXXX  X XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX BBBBBX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX XXXXX
                XXXXXX
                    XXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXX XXXXX
                        XXXXXXXX
                            XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX XXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXX XX XXXXX
                        XXXXXXXX
                            XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XX XX XXXXX
                    	XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XX XX XXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXX XX XXXXX
                        XXXXXXXX
                            XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX           
                        XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXX XXX XXXXX
                    	XXXX XXXXXXXXXXXXXXXXXXXX
                    		XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    		XXXX XXXXXXXXXXXXXXXXXXXXXX
                    	XXXXXX
                        XXXXXXXX
                            XXX XXXXXXXXX X XXX
                            BBB BBBB BB BBBBBBBBBBB
                                XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            XXXXXX
            XXXX XXXXXXXX XXXXXXXXXX XXXXX
                XXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXX XX XXXXX
                        XXXXXXXX
                            XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XX XX XXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XX XX XXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXX XXXX
                        XXXXXXXX
                            XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXX XX XXXXX
                        XXXXXXXX
                            XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXX XX XXXXXXXX XXX
                        XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXX XXX XXX XX XXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXX XXX XXX XXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX