BB BBBBBBBBBBBB

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXX
                        XXXXXXX XXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                BBB BBBBBB BB BBBBBBBBBBBB
                    XXXX XXXXXXXXXXX XXX XX XXXXXXXX
                        XX XXXXXXBBB BBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
                            BBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
                            BBBBB
                        XXXX
                    XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
    XXXXXXXXXX

BBBBB