BBBB BBBBBBBBBBB

    XXXX BBB BBBBB BB BBBBBBBBBBBB
        XXXXX
            XX XXXXXXBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXX
                BBBB
                    XXXXXXX
                BBBBB
            XXXX
        XXXXXX
    BBBBBB XXX

XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBX XX
XXXXXXXXXXX
XXXXXXX XX XX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBX XX
XXXXXXXXXXXX
XXXX BB BBB BBBBBBBBBB XXXXXXXXXX BBBBB XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX

        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBX XX
            XXXX
                XXXX XXXX
                    XX XXXXXXXXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBX XX
                    XXXX
                XXXXX XXX
                BBB BBBBB BB BBBBBBBBBBBB
                    XXXX
                        BB BBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
                                XXXX XXXXXX XX
                            XXXX
                        BBBB
                            XX XXXXXXBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
                                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXXX                            
                        BBBBB
                    XXXXX
                BBBBBB
            XXXXX
        XXXXXX

    XXXXXX
XXXXXXXXXX