BBBB BBBBBBBBBBB

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXX XX XXXXX
                    XXXXXXXXXXXXXX XXXXXX X XXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX

            BBB BBBB BB BBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBXX
                            BB BBBBBBBBBB
                                XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            BBBB
                                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                        XXXX
                    XXXXXX
                    XXXX
                        XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBXXFFFFFFFFFFFFFFFFXXXX
                    XXXXX
                XXXXXX
            BBBBBB

        XXXXXX
    XXXXXX
XXXXXXXXXX
