BBBB BBBBBBBBBBB

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXX XX XXXXX
                    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX

            BBB BBBBB BB BBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
                    BB BBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX 
                    BBBB
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX                     
                    BBBBB
                XXXX
            XXXXXX
            BBBBBB

        XXXXXX
    XXXXXX
XXXXXXXXXX