# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs_from', to=settings.AUTH_USER_MODEL, verbose_name='User from')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs_to', to=settings.AUTH_USER_MODEL, verbose_name='User to')),
            ],
            options={
                'verbose_name': 'Dialog',
                'ordering': ['-date'],
                'verbose_name_plural': 'Dialogs',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messager.Dialog', verbose_name='Dialog')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_messages', to=settings.AUTH_USER_MODEL, verbose_name='User from')),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['-date'],
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
