BB BBBBB
BBBB BBBBBBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXX
                    XXXXXXX XXXXXXXX
                    BB BBBBBBBBBBBB BB BBBBBB
                        XXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                    BBBBB
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                    XXXXX XXXXXXXXX
                    XXXXXXXXXXXXX
                    XXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXX

                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX

XXXX     XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXX
                    XXXXXXX XXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXX
                    XXXXX XXXXXXXXXXXXXX
                        BBBBBBBBBB 
                        XXX
                            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX 
                            FFFFFFFFFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXX
                            XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX 
                            FFFFFFFFFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXX
                            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX 
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX XXX
BBBBB