BBBB BBBBBBBBBBB BBBBBB

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXX XX XXXXX
                    XXXXXXXXXXX XXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX

            BBB BBBBB BB BBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
                    BB BBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX 
                    BBBB
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX                     
                    BBBBB
                XXXX
            XXXXXX
            BBBBBB

        XXXXXX
    XXXXXX
XXXXXXXXXX