# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='article/thumbnail'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article', verbose_name='Image'),
        ),
    ]
