# Generated by Django 2.0.3 on 2018-04-12 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20171119_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogViewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Blog Viewed',
                'verbose_name_plural': 'Blog Vieweds',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='viewed',
            field=models.PositiveIntegerField(default=0, verbose_name='Viewed'),
        ),
        migrations.AddField(
            model_name='blogviewed',
            name='blog_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_viewed', to='blog.Blog', verbose_name='Blog_page'),
        ),
        migrations.AddField(
            model_name='blogviewed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_user_viewed', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
