# Generated by Django 2.0.3 on 2018-06-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='animals',
            field=models.ManyToManyField(blank=True, to='animal.Animal'),
        ),
    ]
