# Generated by Django 2.0.3 on 2018-04-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
    ]
