# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='profile/avatar/thumbnail'),
        ),
    ]
