# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_avatar_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimages',
            name='image_thumb',
            field=models.ImageField(default=1, upload_to='profile/images/thumbnail'),
            preserve_default=False,
        ),
    ]
