# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0005_profile_hobbies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileViewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_viewed', to=settings.AUTH_USER_MODEL, verbose_name='Profile_page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_viewed', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile Viewed',
                'verbose_name_plural': 'Profiles Vieweds',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='viewed',
            field=models.PositiveIntegerField(default=0, verbose_name='Viewed'),
        ),
    ]
