# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0006_auto_20170815_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find', models.CharField(blank=True, choices=[('M', 'Men'), ('W', 'Woman')], max_length=2, verbose_name='I find')),
                ('purpose', models.CharField(blank=True, choices=[('CMN', 'Communicate'), ('FNF', 'Find new friends'), ('GOD', 'Go on a date')], max_length=3, verbose_name='Purpose of dating')),
                ('about_me', models.TimeField(blank=True, verbose_name='About me')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile About',
                'verbose_name_plural': 'Profiles About',
            },
        ),
    ]
