# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20170821_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last date of visit'),
        ),
    ]
