# Generated by Django 2.0.3 on 2018-04-16 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20180412_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='City', to='refdata.City', verbose_name='city'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
