# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Banner name')),
                ('content', tinymce.models.HTMLField(verbose_name='Banner content')),
                ('status', models.BooleanField(default=False, verbose_name='Active status')),
            ],
            options={
                'verbose_name_plural': 'Banners',
                'verbose_name': 'Banner',
            },
        ),
    ]
