# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('url', models.URLField(max_length=50, verbose_name='Url')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('slug', models.SlugField(blank=True, max_length=30, null=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Alt menu',
                'verbose_name': 'Alt menu',
                'ordering': ['order'],
            },
        ),
    ]
