# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0002_altmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('vk', 'Vkontakte'), ('ok', 'Odnoklassniki'), ('fb', 'Facebook'), ('in', 'Instagram')], max_length=2, verbose_name='Title')),
                ('url', models.URLField(max_length=50, verbose_name='Url')),
            ],
            options={
                'verbose_name_plural': 'Social links',
                'verbose_name': 'Social link',
            },
        ),
    ]
