# Generated by Django 2.0.3 on 2018-04-16 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0003_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Name ru')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name en')),
                ('region', models.CharField(max_length=2, verbose_name='Region')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('latitude', models.FloatField(max_length=10.6, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(max_length=10.6, null=True, verbose_name='Longitude')),
                ('population', models.IntegerField(default=0, null=True, verbose_name='Population')),
                ('ontop', models.IntegerField(default=0, null=True, verbose_name='On top')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'verbose_name': 'City',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Name ru')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name en')),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
            ],
            options={
                'verbose_name_plural': 'Countrys',
                'verbose_name': 'Country',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.Country', verbose_name='Country'),
        ),
    ]
