# Generated by Django 2.0.3 on 2018-04-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0004_auto_20180416_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Banner'),
        ),
    ]
