# Generated by Django 2.0.3 on 2018-06-21 12:51

from django.db import migrations, models
import dry_library.backend.thumbnails


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0006_remove_banner_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('srcimage', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Исходное изображение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logo/thumbnail', verbose_name='Изображение')),
                ('status', models.BooleanField(default=False, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Логотип фильтра',
                'verbose_name_plural': 'Логотипы фильтра',
            },
            bases=(dry_library.backend.thumbnails.CreateThumbnail, models.Model),
        ),
    ]
