# Generated by Django 2.0.3 on 2018-07-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0007_filterlogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altmenu',
            options={'ordering': ['order'], 'verbose_name': 'Дополнительное меню', 'verbose_name_plural': 'Дополнительное меню'},
        ),
    ]
