# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dry_library.backend.thumbnails


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nickname')),
                ('gender', models.CharField(choices=[('B', 'Boy'), ('G', 'Girl')], max_length=1, null=True, verbose_name='Gender')),
                ('info', models.TextField(blank=True, null=True, verbose_name='About animal')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='animal/avatar', verbose_name='Avatar')),
                ('avatar_thumb', models.ImageField(blank=True, null=True, upload_to='animal/avatar/thumbnail')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
            },
            bases=(dry_library.backend.thumbnails.CreateThumbnail, models.Model),
        ),
        migrations.CreateModel(
            name='AnimalAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Value attribute')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr', to='animal.Animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Animal attribute',
                'verbose_name_plural': 'Animal attributes',
            },
        ),
        migrations.CreateModel(
            name='KindAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=250, verbose_name='Kind animal (dog, cat...)')),
                ('avatar', models.ImageField(upload_to='animal/kind/avatar', verbose_name='Pictogram animal')),
                ('avatar_thumb', models.ImageField(blank=True, null=True, upload_to='animal/kind/avatar/thumbnail')),
            ],
            options={
                'verbose_name': 'Kind animal',
                'verbose_name_plural': 'Kinds animals',
            },
            bases=(dry_library.backend.thumbnails.CreateThumbnail, models.Model),
        ),
        migrations.CreateModel(
            name='KindAnimalAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(max_length=100, verbose_name='Name attr(weight, color...)')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='animal.KindAnimal', verbose_name='Kind animal')),
            ],
            options={
                'verbose_name': 'Kind attribute',
                'verbose_name_plural': 'Kind attributes',
            },
        ),
        migrations.AddField(
            model_name='animalattr',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.KindAnimalAttr', verbose_name='Attributes'),
        ),
        migrations.AddField(
            model_name='animalattr',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.KindAnimal', verbose_name='Kind animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='animal.KindAnimal', verbose_name='Kind animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amimals', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
