# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kindanimal',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='kindanimal',
            name='avatar_thumb',
        ),
    ]
