# Generated by Django 2.0.3 on 2018-03-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_auto_20170824_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='animals', to='animal.KindAnimal', verbose_name='Kind animal'),
        ),
        migrations.AlterField(
            model_name='animalattr',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='animal.KindAnimalAttr', verbose_name='Attributes'),
        ),
        migrations.AlterField(
            model_name='animalattr',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='animal.KindAnimal', verbose_name='Kind animal'),
        ),
    ]
