# Generated by Django 2.0.3 on 2018-03-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_auto_20180323_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalAttrVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Value attribute')),
            ],
            options={
                'verbose_name_plural': 'Animal attribute values',
                'verbose_name': 'Animal attribute value',
            },
        ),
        migrations.AlterField(
            model_name='animalattr',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='values', to='animal.AnimalAttrVal', verbose_name='Attr animal value'),
        ),
    ]
