# Generated by Django 2.0.3 on 2018-03-27 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_auto_20180327_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindAnimalAttrVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(max_length=100, verbose_name='attr val(blue, 40kg...)')),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrvals', to='animal.KindAnimalAttr', verbose_name='Kind animal attr')),
            ],
            options={
                'verbose_name': 'Kind attribute value',
                'verbose_name_plural': 'Kind attribute values',
            },
        ),
        migrations.AlterField(
            model_name='animal',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='animal.KindAnimal', verbose_name='Kind animal'),
        ),
        migrations.AlterField(
            model_name='animalattr',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='animal.KindAnimalAttrVal', verbose_name='Attr animal value'),
        ),
        migrations.DeleteModel(
            name='AnimalAttrVal',
        ),
    ]
