# Generated by Django 2.0.3 on 2018-03-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_auto_20180327_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kindanimalattrval',
            old_name='val',
            new_name='value',
        ),
    ]
