# Generated by Django 2.0.3 on 2018-03-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0008_animal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(blank=True, choices=[('H', 'В поиске хозяина'), ('P', 'В поиске пары')], max_length=1, null=True, verbose_name='Status'),
        ),
    ]
