# Generated by Django 2.0.3 on 2018-04-17 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0009_auto_20180327_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalattr',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnimalAttr', to='animal.Animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='animalattr',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attribues', to='animal.KindAnimalAttr', verbose_name='Attributes'),
        ),
        migrations.AlterField(
            model_name='animalattr',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kinds', to='animal.KindAnimal', verbose_name='Kind animal'),
        ),
    ]
