# Generated by Django 2.0.3 on 2018-06-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0010_auto_20180417_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='animal/avatar', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('B', 'Мальчик'), ('G', 'Девочка')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='О животном'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='animal.KindAnimal', verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(blank=True, choices=[('H', 'В поиске хозяина'), ('P', 'В поиске пары')], max_length=1, null=True, verbose_name='Статус'),
        ),
    ]
