# Generated by Django 2.0.3 on 2018-06-29 10:16

from django.db import migrations, models
import django.db.models.deletion
import dry_library.backend.thumbnails


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0011_auto_20180628_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(upload_to='animal/photo', verbose_name='Фотография')),
                ('photo_thumb', models.ImageField(blank=True, null=True, upload_to='animal/photo/thumbnail')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnimalPhoto', to='animal.Animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'AnimalPhoto',
                'verbose_name_plural': 'AnimalPhotos',
            },
            bases=(dry_library.backend.thumbnails.CreateThumbnail, models.Model),
        ),
    ]
