# Generated by Django 2.0.3 on 2018-06-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0013_animalviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='viewed',
            field=models.PositiveIntegerField(default=0, verbose_name='Viewed'),
        ),
    ]
