BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB

BBBBB BBBBBBB
    XXXXXXXXXX X BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBXXXXX
    BBB BBBBBBB BB BBBBBBBB
        XXXX BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBX
            XXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXX
            BBBBB
            XXXXXXX
            XXXXXXX
        XXXXXX
    BBBBBB
    XXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXX
BBBBBBBB