BBBB BBBBBBBBBBB

BB BBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
                XX XXXXXXXXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
                XXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXX
                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXX
                        XXX XXXXXXXXXXX XXXXXXXXXXXXXX
                            XXX XXXXXXXXXX XXX XX XXX XXXXXXXXXX XXXX XXXXXXXXXXX
                                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX
                            XXX XXXXXXXXXX XXX XX XXX XXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX
                        XXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXX XXXXX
                        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBBB