# Generated by Django 2.0.3 on 2018-06-21 12:32

from django.db import migrations, models
import dry_library.backend.thumbnails


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='home/logo', verbose_name='Логотип')),
                ('logo_thumb', models.ImageField(blank=True, null=True, upload_to='home/logo/thumbnail')),
            ],
            options={
                'verbose_name_plural': 'FilterLogos',
                'verbose_name': 'FilterLogo',
            },
            bases=(dry_library.backend.thumbnails.CreateThumbnail, models.Model),
        ),
    ]
