# Generated by Django 2.0.3 on 2018-06-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterLogo',
        ),
    ]
