    BBB BBBBBBB BB BBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXX
              XXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXX XXX XXXX
              XX XXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX
              XXXFFFFFFFFFFF FFFFXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXX XXXXX
              XXXFFFFFFFFFFFFFFFFFFFFFFFFFFXXXX
              XXXX XXXXXXXXXX XXX XXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
    BBBBBB