BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX
	XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXX XXX XX XX XXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
                BBB BBBB BB BBBBB
                  XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
                    BBBBBBB  BBBBBBBBBB BBBB
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                    XXXX XXXXXXXXXXXXXXXXXXXXX
                                BBBBB
                            XXXXXX
                        BBBBB
                        XXXXX XXXXXXXXXXXX XXXXXXXXXX
                            BB BBB BBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBB
                                
                            BBBB
                                 
                            BBBBB
                        XXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXX
                        BBBBB
                        XXXXX XXXXXXXXXXXX XXXXXXXXXX
                            BB BBB BBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBB
                                
                            BBBB
                                 
                            BBBBB
                        XXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB

                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXX XXXXX X XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                        BBBBB

                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXX XXXXX X XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                        BBBBB

                  XXXXX
                BBBBBB
            XXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXX XX XX XXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXXX


  XXXX XXX XXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX



    XXXXXXXX
    	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXX
        XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXX
                XXXXXXX XXXXX
                XXXXXXXX XXXXXXXXXXX
                XXXXXXXXX XXXXXXXXXXX
            XXXX
        X

        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX X XXX XXXXXXXXXXX
            XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXX
                XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
            XXXXX
                XXXXXXXX X XXXX
            X
            XXXXXXX X  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXX XXXXXXXXXXXXXXXXXXXX X 
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXX X XXXXXX XXXXXXXXXXX XXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXX X X X X XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X
                        XXXXX X XXX X XXXXXX X 
                    XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX

        XXXXXXXXXX XX X
            XXX XXXXXXXXXXXX
            XX XXXXXXXXX XXXXXX XXXXXXX XXXXX XXX XXXXXX
            XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX X XXXXX X XXXXX
            XXX XXXXXXX X XXXXXXXXX X XXXXX X XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX XX X X XXXXXXXXX
            XXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXX XXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXX X
                XX XXXXXX XXX XXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX X X XXXXXXXXXXXXXX
                XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXX XXXXXX
                XX XXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXX
                    XXXXXXX
                X
                XX XXXXXX XXXXXXX
                XX XXXXXXXXXXX X
                    XXXXXXXXX XXXXXX XXXXXX
                    XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX X XXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXXXXXXXX
                    XXXXXXX XXXX
                    XXX XXXXXXXXX X XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX

                    XXX XXXXXXX X XX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXX X XXXXXXXXX X XXXX X
                            XXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXX XXXXXXX
                            XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX
                            XXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXX
                    XX
                    XX XXXX XX XXXX XXXXXX XX XXXX X XXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
                        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX XXXXXXX
                            XXXXXXX XXXXXXXXXX
                            XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXX
                    XXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX

                    XX XXXX XXXXX XXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXX XX XXX
                        X
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        X
                    XXX

                    XX XXXX XXXXXX XX XXX XXX XXXXXXX
                    XXX XXXXXXXXX X XX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XX X XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXX XX XX X XXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXX X X XXXXXXXXX X X XXXXXX X X XXXXXXXXXXX X  X XXXXX X X XXXXXXXXXXX
                            XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXX XXXXX XXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        X
                        XXXXXXXXX X XXX
                    XXX

                    XX XXX XXX XXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                    XX XXXXXX XXXXXXX
                X XXXX XX XXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXXXXXXXXX
                    XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXX XXXXXXX X XXXXXXX
                X XXXX XX XXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXX XXXXXXX X X XXXXXXXXXXXXXX

                    XXXXXXXXXXXXXXX XXX XXXXXX
                        XXXXXXXXXXX X XXXXXX
                        XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                    X
                    XXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXX X XXXXXXXXXX X XXXXXXXXXXX
                        XXX XXXXXX X XXX
                        XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXX X XXX 
                        XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX X
                            XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                    
                        XXX
                        XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXX XXXXXX
                            XXXXXXXXXXXXX
                        X
                        XXXXX
                            XXXXXXXX XX XXXX XXX XXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   
                        X
                    X
                X XXXX XX XXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX X
                    XXX XXXXXX X XXXXXXXXXX X XXXXXXXXXXX
                    XXX XXXXXX X XXX
                    XX XXX XXXXX XXX XXXXXXX XX XXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX X
                        XXXX XX
                            XX XXXXXXX
                            XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXX
                        XXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX
                            XXXXXXX
                    X
                    XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                X
                 XXXX X
                    XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
                X
            XX

            XX XXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                    XX XXXXX XXXX
                    XXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX XXXXXXXX
                            XXXXXXX XXXXXX
                        XXXX
                    X

                    XX XXXX XXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXX XXXXXXX
                        XXXXXXX XXXXXX
                    XXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
            XXX
            XX XXXXXXX XXXXXXXXX
            XXXXXXXXXXXXX X XXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXX XX XXXX XXXXXXXXX
                XXXXXX XXXX
                BB BBBBBBBBB

                    XX XXXX XXXX
                    
                    XX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX XXXXXXX
                            XXXXXXX X
                        XXXX

                        XXXXXXXXXXXXXXXXXXXXXXXX
                    XX

                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                BBBBB
                XX
            XXXXXXXXXXXXXX X XXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXX
            X
        XXX
    XXXXXXXXX
BBBBBBBB


