BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB

BBBBB BBBBBBB
     
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXX
                    XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXX
                    XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXX XXX XXXXXX XXXXXXX XXX XXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXXX XXXXXXXXXX XXX XXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX

BBBBBBBB