BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBB

BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXX
                    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXX
                    XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXX
                            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX 
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF 
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XXXXX XXX XXXXXXXXX XXXXXX XXXXXX XXXXX X XXXXXXX XXXXXXXXXXXXXXXXX
                        XXXX
                        XXX
                            XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
                        XXX
                            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXX
                            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXXX XXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                        XXXXXXXX
                            XXX XXXXXXXXX X XXX
                            BBB BBBB BB BBBBBBBBBBB
                                XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                            BBBBBB
                            XXX XXXXXXXXXXXXXXX X BB BBBBBBBBBBBBXXBBBBXXBBBBBX
                            XXX XXXXXXXXXXXXXXXXX X BB BBBBBBBBBBBBXXBBBBXXBBBBBX
                        XXXXXXXXX

                        XXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXX
                            XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXX
                            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFF FFFFFFFFFFF
                        XXXX
                        XXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXX
                            XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX

                        XXX
                            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX 
                            FFFFFFFFFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXX
                            XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX 
                            FFFFFFFFFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXX
                            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX 
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF FFFFFF
                        XXXX

                        BB BBBBBBBBBBBB BB BBBBBB
                        XXXX XXXXXXXXXX XXX XXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXX XXXXXXXXXX
                        XXXXXX
                        BBBBB
                        XXXX XXXXXXXXXX XXX XXXXXXXX
                            XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX

BBBBBBBB
BBBBB BB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB
XXXXXXX
XXXXXXX