BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBB

BBBBB BBBBBBB

XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	 
	XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
			XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXX XXXXX
					XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
			XXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXX XXXXX
					XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				        BBBBBBBBBB
				        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
                        XXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF
                        XXXX
				        XXXX XXXXXXXXXX XXX XXXXXXXX
				        	XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
				        	XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
				        XXXXXX
				    XXXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXXXXXX

BBBBBBBB