BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB

BBBBB BBBBBBB
	 
	XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
			XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXX XXXXX
					XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
			XXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXX XXXXX
					XXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXX
				    XXXXX XXXXXXXXXXXXXX
				        BBBBBBBBBB
				        XXXX XXXXXXXXXX XXX XXXXXXXX
				        	XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
				        	XXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
				        XXXXXX
				    XXXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXXXXXX

BBBBBBBB