BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB

BBBBB BBBBBBB
	 
	XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
			XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXX XXXXX
					XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
			XXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXX XXXXX
					XXXXXXXXXXX XXXXXXXX XXXX
			        XXXX XXXXXXXXXX XXX XXXXXXXX
			        	XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
			        XXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXXXXXX

BBBBBBBB