BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBB

BBBBB BBBBBBB
     
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXX
                    XXXXXXXXX XXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXX
                    XXXXX XXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXX
                            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXX
                            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXX
                            FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFF
                        XXXX
                        XXXX XXXXXXXXXX XXX XXXXXXXX
                            XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX

BBBBBBBB