BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBBB BBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX        
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBB        
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
    
     #

     #

BBBBBBBB
BBBBB BB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB